### PR TITLE
Generate 8 spaces instead 2 spaces (#303)

### LINKED ISSUE #303: ghc (and ghc-lib-parser-9.10.1.20240511) no longer builds with happy 2.0
I know this is a downstream change, but since it is used across the ecosystem, I figured I would report it here (maybe it's a "happy" bug?). When installing fourmolu, which depends on `ghc-lib-parser`, I get the following error:

```sh
[416 of 447] Compiling GHC.Parser       ( dist/build/GHC/Parser.hs, dist/build/GHC/Parser.o, dist/build/GHC/Parser.dyn_o )

dist/build/GHC/Parser.hs:5975:24: error: [GHC-58481]
    parse error on input ‘<-’
    Suggested fix: Possibly caused by a missing 'do'?
     |
5975 |                   ; mg <- mkPatSynMatchGroup name happy_var_5
     |                        ^^
```

Maybe the version bound is not tight enough in `ghc-lib-parser`? Anyway, seems like libraries that depend on `happy` are breaking 😓

### PR DESCRIPTION
**Pull request by sgraf812**
2 spaces forced a breaking change on GHC. Fixes #303.

Let me try on GHC before merging.

### CODE REVIEW

**Comment by sgraf812** [comment]
I can confirm that this fixes the GHC build. Will merge soon and upload a release afterwards.
