### ISSUE TITLE
ghc (and ghc-lib-parser-9.10.1.20240511) no longer builds with happy 2.0

### ISSUE THREAD

**Issue by Tritlo** [haskell/happy#303]
I know this is a downstream change, but since it is used across the ecosystem, I figured I would report it here (maybe it's a "happy" bug?). When installing fourmolu, which depends on `ghc-lib-parser`, I get the following error:

```sh
[416 of 447] Compiling GHC.Parser       ( dist/build/GHC/Parser.hs, dist/build/GHC/Parser.o, dist/build/GHC/Parser.dyn_o )

dist/build/GHC/Parser.hs:5975:24: error: [GHC-58481]
    parse error on input ‘<-’
    Suggested fix: Possibly caused by a missing 'do'?
     |
5975 |                   ; mg <- mkPatSynMatchGroup name happy_var_5
     |                        ^^
```

Maybe the version bound is not tight enough in `ghc-lib-parser`? Anyway, seems like libraries that depend on `happy` are breaking 😓

**Comment by phadej** [comment]
`ghc-lib-parser` doesn't have upper bounds on `happy`, e.g.

```
build-tool-depends: alex:alex >= 3.1, happy:happy > 1.20
```

I couldn't test whether GHC proper is buildable with `happy-2.0` (https://gitlab.haskell.org/ghc/ghc/-/issues/25276); I'd expect that it should be, as happy-2.0 doesn't mention any changes to the formats. If it isn't, I'd consider it a bug in `happy-2.0`.

**Comment by Tritlo** [comment]
If you do `cabal update` and try to install `fourmolu` (which depends on `ghc-lib-parser`), you'll see this bug!

**Comment by phadej** [comment]
>  you'll see this bug!

I meant that if GHC proper fails to build with `happy-2.0`, then arguably a bug is in `happy-2.0` (at least in changelog as "everything is broken"); if GHC proper however builds fine, then the issue is in `ghc-lib-parser`.

But GHC proper is not buildable, I see

```
_build_master/stage0/compiler/build/GHC/Parser.hs:6113:24: error: [GHC-58481]
    parse error on input ‘<-’
    Suggested fix: Possibly caused by a missing 'do'?
     |
6113 |                   ; mg <- mkPatSynMatchGroup name happy_var_5
     |                        ^^
Command failed
```

... so the something wrong with `happy-2.0`

**Comment by phadej** [comment]
This looks like a breaking change caused by tab-to-spaces change.

**Comment by int-index** [comment]
Alright, so it's not a bug. `happy` does not guarantee the layout of the code it emits. Still, we should avoid _unnecessary_ breakage, so I suggest emitting 8 spaces instead of tabs (fbc1896abc24116cf50b539fd247ae519bb35062 uses 2 spaces)

**Comment by Tritlo** [comment]
> Alright, so it's not a bug in a strict sense. `happy` offers no guarantees about the layout of the code it emits. Still, we should avoid _unnecessary_ breakage, so I suggest emitting 8 spaces instead of tabs ([fbc1896](https://github.com/haskell/happy/commit/fbc1896abc24116cf50b539fd247ae519bb35062) uses 2 spaces)

I mean, `happy` should *at least* work for GHC, right?

**Comment by sgraf812** [comment]
It's generally a bad idea to use layout in happy-generated parsers. For example, `happy` will not attempt to strip whitespace to keep the alignment with the start of the `{%` line. It's IMO shear coincidence that GHC builds with the code as-is. I have debugged such errors myself multiple times while working on GHC's parsers.

That said, it's an unforced change and I'm unsure if increasing to 8 spaces will fix the problem.

Perhaps revert fbc1896abc24116cf50b539fd247ae519bb35062 or otherwise make the space character configurable?

**Comment by sgraf812** [comment]
Version 2.0 has been deprecated and 2.0.1 with the fix has been uploaded. @Tritlo, could you try again?

**Comment by Tritlo** [comment]
> Version 2.0 has been deprecated and 2.0.1 with the fix has been uploaded. @Tritlo, could you try again?

Yes, it's working again. Thanks for the quick response!
